id: P249B5BC2
initial_creation_type: ocr
source_metadata:
  volumes:
    43b8f3977df1465eb0366ba925abc91e:
      base_file: v076.txt
      image_group_id: I1PD95921
      title: དོན་གསང་བ་རྣམ་པར་ཕྱེ་བ་བསྡུས་ཏེ་བཤད་པ།
      total_pages: 1774
      volume_number: 76
